---
- name: Download the ISO of CENTUM-VP {{ ctmvp_revision }}
  community.windows.win_robocopy:
    src: \\{{ sw_src_path }}\CENTUM-VP\{{ ctmvp_revision }}
    dest: '{{ win_local_sw_depot }}\CENTUM-VP\{{ ctmvp_revision }}'
    flags: /S

- name: Mount the ISO of CENTUM-VP {{ ctmvp_revision }}

  community.windows.win_disk_image:
    image_path: '{{ local_ctmvp_depot }}\CENTUM-VP_{{ ctmvp_revision }}.iso'
    state: present
  register: mount_centumvp
  retries: 5
  delay: 3
  until: "mount_centumvp is succeeded"

- name: Copy CENTUM-VP installer files from mounted iso to local depot
  community.windows.win_robocopy:
    src: '{{ mount_centumvp.mount_paths[0] }}'
    dest: '{{ local_ctmvp_depot }}'
    flags: /S /ZB /R:5 /W:5

- name: Set read and execute permissions for Everyone on the CENTUM-VP software depot
  ansible.windows.win_acl:
    user: Everyone
    path: '{{ local_ctmvp_depot }}'
    rights: ReadAndExecute
    type: allow

- name: Unmount the ISO of CENTUM-VP {{ ctmvp_revision }}
  community.windows.win_disk_image:
    image_path: '{{ local_ctmvp_depot }}\CENTUM-VP_{{ ctmvp_revision }}.iso'
    state: absent

- name: Delete the ISO of CENTUM-VP {{ ctmvp_revision }}
  ansible.windows.win_file:
    path: '{{ local_ctmvp_depot }}\CENTUM-VP_{{ ctmvp_revision }}.iso'
    state: absent

- name: Edit CENTUMSetup.exe.config file
  community.windows.win_lineinfile:
    dest: '{{ local_ctmvp_depot }}\CENTUM\INSTALL\CENTUMSetup.exe.config'
    backrefs: true
    state: present
    regexp: '<add key="ACCESSRIGHTS_MODE" value="CTM"\/>'
    line: '<add key="ACCESSRIGHTS_MODE" value="CTM /R"/>'

- name: Download AutoIt
  community.windows.win_robocopy:
    src: \\{{ sw_src_path }}\AutoIt
    dest: '{{ win_local_sw_depot }}\AutoIt'
    flags: /E
