---
- name: Deploy all PRM group hosts
  hosts: PRM
  vars_files:
    - MyProject_vars.yaml

  roles:
    - win_os_settings
    - { role: join_domain_other, when: using_active_directory }
    - win_local_users
    - yoko_win_settings
    - { role: prm, prm_revision: 'R4.06.00' }
    - { role: vsr, when: not using_active_directory }
    - { role: trellix_ens, when: not using_active_directory }
