---
galaxy_info:
  author: Clement Buurman
  description: Installs SQL Native Client
  company: Yokogawa Europe Solutions B.V.
  license: none
  min_ansible_version: '2.12.5'
  platforms:
    - name: Windows
      release:
        - 2016
        - 2019
        - 2022
  galaxy_tags: []

dependencies:
  - role: win_local_sw_depot
