---
galaxy_info:
  author: Michael van Dooren / Clement Buurman
  description: Installs Trellix ePO.
               Checks in all packages and extensions as per manual.
               Creates all mandatory groups in the system tree and applies correct policies.
  company: Yokogawa Europe Solutions B.V.
  license: none
  min_ansible_version: '2.12.5'
  platforms:
    - name: Windows
      release:
        - 2016
        - 2019
        - 2022
  galaxy_tags: []

dependencies:
  - role: win_local_sw_depot
  - { role: vcredist, vcredist_versions: { 2010, 2013, 2022 } }
  - role: sql_expr_2019_add_instance
  - role: ms_ole_db
