---
galaxy_info:
  author: Michael van Dooren / Clement Buurman
  description: Installs Veritas System Recovery 21.0.3 (or 18.0.4 if specified in project vars file)
  company: Yokogawa Europe Solutions B.V.
  license: none
  min_ansible_version: '2.10.6'
  platforms:
    - name: Windows
      release:
        - 2016
        - 2019
        - 2022
  galaxy_tags: []

dependencies:
  - role: win_local_sw_depot
  - { role: vcredist, vcredist_versions: { 2022 } }
