---
- name: Delete all current backup tasks
  ansible.windows.win_shell: '{{ win_local_sw_depot }}\Veritas_System_Recovery\{{ vsr_ver }}\Docs\Automation\PowershellScripts\RemoveAllJobs.ps1'
  changed_when: false

- name: Deploy Backup Task script
  ansible.windows.win_template:
    src: AddImageJob.ps1
    dest: '{{ win_local_sw_depot }}\Veritas_System_Recovery\{{ vsr_ver }}\Docs\Automation\PowershellScripts\AnsibleAddImageJob.ps1'

- name: Create Backup Task {{ vsr_backup_interval }}
  ansible.windows.win_shell: '{{ win_local_sw_depot }}\Veritas_System_Recovery\{{ vsr_ver }}\Docs\Automation\PowershellScripts\AnsibleAddImageJob.ps1'
  register: backup
  changed_when: false
