---
- name: Download NVIDIA Quadro P620 GPU Drivers
  community.windows.win_robocopy:
    src: \\{{ sw_src_path }}\Drivers\nVidia\quadro-rtx-winserv\536.67
    dest: '{{ win_local_sw_depot }}'
    flags: /E

- name: Install NVIDIA Quadro P620 GPU Drivers
  ansible.windows.win_command:
    cmd: '{{ win_local_sw_depot }}\Drivers\nVidia\quadro-rtx-winserv\536.67\setup.exe'
    argv: '-s'
  register: nvidia_driver

- name: Reboot if required
  ansible.windows.win_reboot:
  when: nvidia_driver.reboot_required
