---
- name: Enable Hyper-V feature
  ansible.windows.win_feature:
    name: Hyper-V
    state: present
    include_management_tools: true
  register: enable_hyperv_feature

- name: Reboot if required
  ansible.windows.win_reboot:
  when: enable_hyperv_feature.reboot_required

- name: Check if volume exists {{ datastore_volume_name }}
  ansible.windows.win_shell: |
    if (Get-Volume -FilesystemLabel {{ datastore_volume_name }} -ErrorAction SilentlyContinue) {
      Write-Host true
    } else {
      Write-Host false
    }
  changed_when: false
  register: datastore_volume_exists

- name: Prepare the DATASTORE volume
  ansible.builtin.include_tasks: st_prepare_datastore.yml
  when: datastore_volume_exists.stdout_lines[0] == "false"

- name: Check if Hyper-V virtual machine exists {{ vm_name }}
  ansible.windows.win_shell: if (Get-VM -Name {{ vm_name }} -ErrorAction SilentlyContinue) {Write-Host true} ELSE {Write-Host false}
  changed_when: false
  register: hyperv_machine_exists

- name: Create new VM with name {{ vm_name }}
  ansible.builtin.include_tasks: st_hyper_v_add_vm.yml
  when: hyperv_machine_exists.stdout_lines[0] == "false"
