---
galaxy_info:
  author: Michael van Dooren / Clement Buurman
  description: Installs Latest keepass version
  company: Yokogawa Europe Solutions B.V.
  license: none
  min_ansible_version: '2.11.6'
  platforms:
    - name: Windows
      release:
        - 2016
        - 2019
        - 2022
  galaxy_tags: []

dependencies:
  - role: win_local_sw_depot
