---
galaxy_info:
  author: Michael van Dooren / Clement Buurman
  description: Installs Dell Open Manage Server Administrator
  company: Yokogawa Europe Solutions B.V.
  license: none
  min_ansible_version: '2.10.6'
  platforms:
    - name: Windows
      release:
        - 2016
        - 2019
        - 2022
  galaxy_tags: []

dependencies:
  - { role: vcredist, vcredist_versions: { 2022 } }
