---
galaxy_info:
  author: Michael van Dooren / Clement Buurman
  description: Set Windows settings that are valid for all Windows hosts
  company: Yokogawa Europe Solutions B.V.
  license: none
  min_ansible_version: '2.10.6'
  platforms:
    - name: Windows
      release:
        - 2016
        - 2019
        - 2022
  galaxy_tags: []

dependencies:
  - role: ms_edge
