---
- name: Deploy IT-Security bootstrap
  ansible.windows.win_template:
    src: it_security_configuration_bootstrap.cmd
    dest: '{{ local_ctmvp_depot }}\it_security_configuration_bootstrap.cmd'

- name: Deploy IT-Security AutoIt script
  ansible.windows.win_template:
    src: it_security_configuration.au3
    dest: '{{ local_ctmvp_depot }}\it_security_configuration.au3'

- name: Set RunOnce in registry to execute the IT-Security bootstrapper at next reboot
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce
    name: itsec
    data: '{{ local_ctmvp_depot }}\it_security_configuration_bootstrap.cmd'
    type: string

- name: Reboot
  ansible.windows.win_reboot:
    msg: Reboot by Y-dPloy to run CENTUM-VP IT-Security tool at next boot
    pre_reboot_delay: 10

- name: Wait for CENTUM-VP IT-Security tool to start
  community.windows.win_wait_for_process:
    process_name_exact: Yokogawa.IA.iPCS.Platform.Security.ITSecurityTool
    state: present
    timeout: 300
    sleep: 5

- name: Wait for CENTUM-VP IT-Security tool to stop
  community.windows.win_wait_for_process:
    process_name_exact: Yokogawa.IA.iPCS.Platform.Security.ITSecurityTool
    state: absent
    timeout: 900
