---
- name: Create local installation media folder for EXA-OPC
  ansible.windows.win_file:
    path: '{{ local_exaopc_depot }}'
    state: directory

- name: Download the ISO of EXA-OPC {{ exaopc_revision }}
  community.windows.win_robocopy:
    src: \\{{ sw_src_path }}\EXA-OPC\{{ exaopc_revision }}
    dest: '{{ local_exaopc_depot }}'
    flags: /E

- name: Mount the ISO of EXA-OPC {{ exaopc_revision }}
  community.windows.win_disk_image:
    image_path: '{{ local_exaopc_depot }}\EXAOPC_{{ exaopc_revision }}.iso'
  register: mount_exaopc

- name: Download EXA-OPC installer files from mounted iso to local depot
  community.windows.win_robocopy:
    src: '{{ mount_exaopc.mount_paths[0] }}'
    dest: '{{ local_exaopc_depot }}'
    flags: /S /Z /XO /R:5 /W:5

- name: Set read and execute permissions for Everyone on the EXA-OPC software depot
  ansible.windows.win_acl:
    user: Everyone
    path: '{{ local_exaopc_depot }}'
    rights: ReadAndExecute
    type: allow

- name: Unmount the ISO of EXA-OPC{{ exaopc_revision }}
  community.windows.win_disk_image:
    image_path: '{{ local_exaopc_depot }}\EXAOPC_{{ exaopc_revision }}.iso'
    state: absent

- name: Delete the ISO of EXA-OPC {{ exaopc_revision }}
  ansible.windows.win_file:
    path: '{{ local_exaopc_depot }}\EXAOPC_{{ exaopc_revision }}.iso'
    state: absent

- name: Download AutoIt
  community.windows.win_robocopy:
    src: \\{{ sw_src_path }}\AutoIt
    dest: '{{ win_local_sw_depot }}\AutoIt'
    flags: /E
