---
galaxy_info:
  author: Michael van Dooren / Clement Buurman
  description: Installs Yokogawa CENTUM-VP software
  company: Yokogawa Europe Solutions B.V.
  license: none
  min_ansible_version: '2.10.6'
  platforms:
    - name: Windows
      release:
        - 2016
        - 2019
        - 2022
  galaxy_tags: []

dependencies:
  - role: win_local_sw_depot
  - { role: vcredist, vcredist_versions: { 2022 } }
  - role: opc_com_proxy_stub
  - role: ms_msedge_webview2
  - role: ms_dotnet
