---
galaxy_info:
  author: Michael van Dooren / Clement Buurman
  description: Prepares a node for the installation of ProSafe-RS R4.05.00
  company: Yokogawa Europe Solutions B.V.
  license: none
  min_ansible_version: '2.10.6'
  platforms:
    - name: Windows
      release:
        - 2016
        - 2019
        - 2022
  galaxy_tags: []

dependencies:
  - role: win_local_sw_depot
  - { role: vcredist, vcredist_versions: { 2022 } }
  - role: opc_com_proxy_stub
  - role: ms_access_db_engine_2016
  - role: ms_dotnet
  - role: yoko_win_settings
